@startuml

class Paleta<T> {
    -sabor: T
    -precio: double
    +Paleta(sabor: T, precio: double)
    +mostrarInformacion(): void
}

class PaletaAgua<T> {
    -baseAgua: boolean
    +PaletaAgua(sabor: T, precio: double, baseAgua: boolean)
    +mostrarBaseAgua(): void
    +nuevoPrecio(): void
    +paletaGrandeOChica(): void
}

class PaletaCrema<T> {
    -cremosa: boolean
    +PaletaCrema(sabor: T, precio: double, cremosa: boolean) throws PrecioNegativoException
    +mostrarBaseCrema(): void
    +nuevoPrecio(): void
    +paletaGrandeOChica(): void
}

class PrecioNegativoException {
    +PrecioNegativoException(mensaje: String)
}

PaletaAgua --|> Paleta
PaletaCrema --|> Paleta
PrecioNegativoException --|> Exception

@enduml
